site_name: Wiperf V2 Documentation
nav:
    - Home: index.md
    - Operation Overview: operation.md
    - Data Server:
        - Splunk:
            - splunk_platform.md
            - splunk_software.md
            - splunk_install.md
            - splunk_configure.md
        - Influx/Grafana:
            - influx_platform.md
            - influx_install.md
            - influx_configure.md
            - grafana_platform.md
            - grafana_install.md
            - grafana_configure.md
    - Probe:
        - probe_platform.md
        - probe_prepare.md
        - probe_install.md
        - probe_configure.md
        - probe_deploy.md
    - Troubleshooting: troubleshooting.md
    - FAQ: faq.md
    - Reference Docs:
        - config.ini.md
        - data_points.md
        - Dashboards:
            - db_probe_summary.md
            - db_speedtest.md
            - db_udp_iperf3.md
            - db_tcp_iperf3.md
            - db_http.md
    - About: about.md
theme:
    name: 'material'
    icon:
        logo: material/wifi
    language: en
extra_css:
  - extra.css
markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
plugins:
    - search
    - git-revision-date-localized
